svmbir_demo
===========

This is a set of examples showing the use and visualization of
data using svmbir reconstructions. 

Installation:
-------------

1. Download and install svmbir and run a demo in that codebase.
2. Create and activate a conda environment using environment.yml.
E.g., from a terminal enter

    ```
    conda env create -f environment.yml
    conda activate svmbir_demo
    ```

3. If svmbir is not installed automatically, then in a terminal, go to
the main `svmbir_demo` directory, with the svmbir_demo conda
environment activated and invoke `pip install <path>/svmbir`
where `<path>` is the path to the `svmbir` directory.



